mklink /J .bash system\.bash 
mklink /J .bashrc system\.bashrc
mklink /J .bash_profile system\.bash_profile
mklink /J .bash_logout system\.bash_logout 
mklink /J .bash-local system\.bash-local-cygwin
mklink /J .astylerc system\.astylerc
mklink /J .cshrc system\.cshrc 
mklink /J .tcsh system\.tcsh 
mklink /J .gemrc system\.gemrc 
mklink /J .gitconfig system\.gitconfig
mklink /J .gitignore system\.gitignore 
mklink /J .hgrc system\.hgrc 
mklink /J .inputrc system\.inputrc
mklink /J .juliarc.jl system\.juliarc.jl
mklink /J .login system\.login 
mklink /J .screenrc system\.screenrc 
mklink /J .tmux.conf system\.tmux.conf 
mklink /J .netrc system\.netrc
mklink /J .profile system\.profile 
mklink /J .vimrc system\.vimrc-cygwin 
mklink /J script system\script
