#!/bin/bash
cd ~
echo "Bash links ..."
ln -sf ./system/.bash .bash
ln -sf ./system/.bashrc .bashrc
ln -sf ./system/.bash_profile .bash_profile
echo "Manually set .bash-local link; linked to ./system/.bash-local-macosx-bored by default"
ln -sf ./system/.bash-local-macosx-bored .bash-local
echo "Profile links ..."
ln -sf ./system/.astylerc .astylerc
ln -sf ./system/.cshrc .cshrc
ln -sf ./system/.tcsh .tcsh
ln -sf ./system/.gemrc .gemrc
ln -sf ./system/.gitconfig .gitconfig
ln -sf ./system/.gitignore .gitignore
ln -sf ./system/.curlrc .curlrc
ln -sf ./system/.hgrc .hgrc
ln -sf ./system/.inputrc .inputrc
ln -sf ./system/.login .login
ln -sf ./system/.screenrc .screenrc
ln -sf ./system/.tmux.conf .tmux.conf
ln -sf ./system/.netrc .netrc
ln -sf ./system/.profile .profile
ln -sf ./system/.vimrc .vimrc
ln -sf ./system/.vim .vim
ln -sf ./system/.juliarc.jl .juliarc.jl
mkdir .julia
mkdir .julia/config
ln -sf ../../system/julia/startup.jl .julia/config/startup.jl
mkdir .ssh
ln -sf ../system/.ssh/config .ssh/config
echo "Script ..."
ln -sf ./system/script script
echo "Sublime ..."
ln -sf ~/system/sublime ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
