#!/usr/local/bin/tcsh
set ddd = $cwd
cd /scr1/monty/apache/pest
cd $1
echo $cwd
mv -f $1-param $1-param_old
echo > $1-param
foreach i ( *.rec )
	../S-param $i:r >> $1-param
	end
cat $1-param
cd $ddd
unset ddd
