#!/usr/local/bin/tcsh
inschek ../p4a-log.dat_grf.ins $1
grep "[x-z]" ../p4a-log.dat_grf.obs | sort > ! $1-1-$$
grep "v" ../p4a-log.dat_grf.obs | sort > ! $1-2-$$
grep "w1. " ../p4a-log.dat_grf.obs | sort > ! $1-3-$$
grep "w2. " ../p4a-log.dat_grf.obs | sort > ! $1-4-$$
grep "w2.[a-z,1-9]" ../p4a-log.dat_grf.obs | sort > ! $1-5-$$
grep "w3" ../p4a-log.dat_grf.obs | sort > ! $1-6-$$
cat $1-1-$$ $1-2-$$ $1-3-$$ $1-4-$$ $1-5-$$ $1-6-$$ > ! $1-$$
rm -f $1-1-$$ $1-2-$$ $1-3-$$ $1-4-$$ $1-5-$$ $1-6-$$ ../p4a-log.dat_grf.obs
paste ../p4.data/AW_s4 $1-$$ > ! $1-awk
awk 'BEGIND{ssq=0}{d=$2-$5;wd=d*d*$3;d=sqrt(wd);ssq=ssq+wd;if($2!=0)rd=d/$2*100;else rd=0;printf "%-5s %10.3f %10.3f %8.3f %10.3f %10.3f %10.3f\n", $1, $2, $5, $3, d, wd, rd} END {print ssq}' $1-awk > ! $1-ssq
rm -f $1-$$ pest.tmp $1-awk
tail -1 $1-ssq
