#!/usr/local/bin/tcsh
\rm -f RERUN 
foreach i ($1.*.dat_grf)
	\rm -f pest.tmp
        inschek ../p4a-log.dat_grf.ins $i >& /dev/null
        @ error = `cat pest.tmp`
        if( $error == 1 ) then
                echo $i
                \rm -f $i
		touch RERUN
        endif
	end
