#!/bin/ksh
param=`head -4 $1.pst | tail -1 | awk '{print $1}'`
line=`grep -n RESULTS $1.rec | awk '{print $1}' | sed 's/://g'`
ssr=`grep "ie phi" $1.rec | awk '{print $9}' | tail -1`
lineres=`tail +$line $1.rec | grep -n value | head -1 | awk '{print $1}' | sed 's/://g'`
let line=line+lineres
tail +$line $1.rec | head -$param | awk '{
	est[NR]=$2
	ll[NR]=$3
	ul[NR]=$4
	NP=NR
}
END{
	for( i = 1; i <= NP; i++ )
		printf( "%g\n", est[i] );
}'
