#!/bin/tcsh
#
# USAGE: xfz Problem_Name

# FEHM
(/scr2/monty/fehm/bin/xfehm_random < $1-in >! $1-out ) >& /dev/null

# AVS-TEC and AVS-GMV
printf "%s\n" $1 > $1-$$
# /scr3/monty/c/avs-gmv/avs-gmv_2dv < $1-$$ >& /dev/null
/scr3/monty/c/avs-tec.uns/avs-tecz < $1-$$ >& /dev/null
rm -f $1-$$ >& /dev/null

# CLEAR
rm -f $1-out $1.his $1.fin >& /dev/null
rm -f $1.10* >& /dev/null
