#!/usr/bin/env bash

esm=()
for i in `seq 1 41`; do
	s=$(printf "es%02d" $i)
	esm+=($s)
done

for i in "${esm[@]}"; do
	echo $i: `ssh -t -o "StrictHostKeyChecking no" $i top -n 1 2>/dev/null | grep Tasks`
done
