#!/bin/tcsh -f
if( $2 == "" ) then
	echo "Usage:" $0 "[node list file] [xyz file]"`
	exit
endif
if( ! -e $1 ) then
	echo "Usage:" $0 "[FEHM zone file]"
	exit
endif
foreach i ( `cat $1`)
	echo -n $i" " 
	sed -n "$i p" $2 
	end
	# grep "^"$i" " $2 
