#!/bin/tcsh -f -f
if( $2 == "" ) then
	echo "Usage:" $0 "[extracted node list file] [flow macro]"`
	exit
endif
if( ! -e $1 ) then
	echo "Usage:" $0 "[FEHM zone file]"
	exit
endif
foreach i ( `cat $1`)
  grep "^"$i" " $2 
  end

