#!/usr/bin/env python

import sys
import fileinput
import os
from os.path import basename

if ( len(sys.argv) == 1 ):
	print "Usage: fehmn2xyz *.fehmn"
	sys.exit()
else:
	print "Case name: %s" % ( sys.argv[:] )

nfile = len(sys.argv) - 1
print "Number of files ", nfile
fehmnfilename = sys.argv[1]
rootname = os.path.splitext(fehmnfilename)[0]
print "Root name ", rootname
if ( rootname == fehmnfilename ):
	fehmnfilename = fehmnfilename + ".fehmn"
with open(fehmnfilename, "r") as f:
	lines = f.readlines()
	f.close()
coord = True
for i in range(0, len(lines)):
	if coord :
		if "coor" in lines[i]:
			# print lines[i].rstrip()
			i=i+1
			splitline = lines[i].split()
			# print lines[i].rstrip()
			numnodes = int(splitline[0]) 
			print "Number of nodes %d" % numnodes
			f = open(rootname+".xyz", 'w')
			for j in range (0, numnodes):
				i=i+1;
				splitline = lines[i].split()
				f.write( "%g %g %g\n" % ( float(splitline[1]), float(splitline[2]), float(splitline[3]) ))
			f.close()
			coord = False
