#!/bin/bash
suffix=`cat ~/script/non-exe-extensions`
# echo $suffix
logf=/tmp/slog.$$
for entry in $suffix; do
    printf "Checking for %15s ... " $entry
        nice find . -name "*.$entry" -type f -exec chmod a-x {} \; >$logf 2>&1
    echo -ne "\\r"
    done
    [ -n $logf ] && echo "For details and errors, see $logf"
    echo "done."
