#!/bin/tcsh -f
foreach i ( *.jpg )
	set p = $i:r
	djpeg -scale 1/2 -targa $i >! $p.tar
        cjpeg -quality 65 $p.tar >! $p.s.jpg
	djpeg -scale 1/8 -gif $p.s.jpg >! $p.gif
	mv -f $p.s.jpg $i
	rm -f $p.tar
	end
