#!/bin/bash
case "$HOSTNAME" in
(hb*) ~/bin/julia-hobo "$@";;
(wf*) ~/bin/julia-wolf "$@";;
(pi*) ~/bin/julia-wolf "$@";;
(ml*) ~/bin/julia-wolf "$@";;
(mp*) ~/bin/julia-mapache "$@";;
(*) ~/bin/julia "$@";;
esac
