#!/bin/bash
case "$HOSTNAME" in
(hb*) ~/bin/julia-hobo "$@";;
(pi*) ~/bin/julia-pinto "$@";;
(ml*) ~/bin/julia-pinto "$@";;
(wf*) ~/bin/julia-pinto "$@";;
(cj*) ~/bin/julia-conejo "$@";;
(mp*) ~/bin/julia-conejo "$@";;
(mads*) /usr/bin/julia "$@";;
(*) ~/bin/julia "$@";;
esac
