#!/bin/bash

killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    echo kill -stop ${_pid}
    kill -stop ${_pid} # needed to stop quickly forking parent from producing child between child killing and parent killing
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
	echo "child pid" ${_child}
        killtree ${_child} ${_sig}
    done
    sleep 1
    echo kill ${_pid}
    kill ${_pid}
    echo kill -${_sig} ${_pid}
    kill -${_sig} ${_pid}
}

if [ $# -eq 0 -o $# -gt 2 ]; then
    echo "Usage: $(basename $0) <pid> [signal]"
    exit 1
fi

killtree $@
kill $@
