#!/usr/bin/env bash

madsnew=()
madsnew+=(madsmin)
for i in `seq 0 29`; do
	s=$(printf "mads%02d" $i)
	madsnew+=($s)
done

for i in "${madsnew[@]}"; do
	echo $i: `ssh -t -o "StrictHostKeyChecking no" vvv@$i top -n 1 2>/dev/null | grep Tasks`
done
