#!/usr/bin/env bash

madsnew=()
madsnew+=(madsmin)
for i in `seq 0 29`; do
	s=$(printf "mads%02d" $i)
	madsnew+=($s)
done

for i in "${madsnew[@]}"; do
	echo $i: `ssh -o "StrictHostKeyChecking no" vvv@$i uptime 2>/dev/null` `ssh -o "StrictHostKeyChecking no" vvv@$i juliadir 2>/dev/null`
done
