#!/bin/tcsh -f
@ job = $1
if( $job == -1 ) then
	echo "Kill all the jobs"
	bjobs | grep -v "JOB" | awk '{print $1}'
	set id = `bjobs | grep -v "JOB" | awk '{print $1}'`
	echo Jobs to be killed $id
	bkill $id
	exit 0
endif
while( $job != 0 )
	set status = `bjobs | grep "^"$job" " | awk '{print $3}'`
	if( $status == PEND ) then
		bjobs -l $job | tr -d '\n' | sed -e 's/   *//g' | tr ',' '\n' | grep Dependency | tr '<>()' ' ' |  awk '{print $4}'
		@ njob = `bjobs -l $job | tr -d '\n' | sed -e 's/   *//g' | tr ',' '\n' | grep Dependency | tr '<>()' ' ' |  awk '{print $4 }'`
		echo $job "->" $njob
		bkill $job
		@ job = $njob
	else
		if( $status == RUN ) then
			echo Job $job is running!
		else
			echo Job $job is missing!
		endif
		@ job = 0
	endif
end
