#!/bin/tcsh -f
        if( -e $1-serial.runs ) then
                @ nSRuns = `cat $1-serial.runs`
        else
                @ nSRuns = 0
		rm -f $1-serial.runs_restart
        endif
        if( -e $1-serial.runs_restart ) then
                @ rSRuns = `cat $1-serial.runs_restart`
		if( $rSRuns != $nSRuns ) then
	                @ rSRuns = $rSRuns + 1
      			unzip -o $1_$rSRuns-serial.zip
			echo 'Reset serial run number ' $rSRuns
	                echo $rSRuns >! $1-serial.runs_restart
               		exit
		else
			rm -f $1-serial.runs_restart	
		endif
        endif
	@ nSRuns = $nSRuns + 1
	touch $1.pest
	rm -f $1_$nSRuns-serial.zip
	zip $1_$nSRuns-serial.zip $1.pest
	echo 'Serial run number ' $nSRuns
	echo $nSRuns >! $1-serial.runs
