#!/bin/tcsh -f
set root = $1:r
set ext = `pest_extensions $root`
# echo Extesnions: $ext
if( -e $root.serial_runs ) then
	setenv serial
	unsetenv jacobian
	setenv new
else if( -e $root.jacobian_runs ) then
	unsetenv serial
	setenv jacobian
	setenv new
	endif
endif
if( $1 == $root ) then
	setenv serial
	unsetenv jacobian
	unsetenv new
endif
if( ${?serial} ) then 
# Serial
        if( -e $root-serial.runs ) then
                @ nSRuns = `cat $root-serial.runs`
        else
                @ nSRuns = 0
	endif
        @ nSRuns = $nSRuns + 1
        echo 'Serial run number ' $nSRuns
        rm -f $root-serial_$nSRuns.zip
	foreach i ( $ext )
	        zip -u $root-serial_$nSRuns.zip $root.$i >& /dev/null
	end
        echo $nSRuns >! $root-serial.runs
	@ ifiles = 0
	if( -e $root-files ) then
		set files = $root-files
		@ ifiles = 1
	else
	if( -e $root.files ) then
		set files = $root.files
		@ ifiles = 1
	endif
	endif
	if( $ifiles == 1 ) then
		set rfin = `cat -n $files | awk '{print $1, $2}' | grep "^5" | awk '{print $2}'`
		set ofin = `cat -n $files | awk '{print $1, $2}' | grep "^6" | awk '{print $2}'`
		if( $ofin != '' && $rfin != '' ) then
			echo Fin files are $rfin $ofin
			if( -e $ofin ) then
				echo mv $ofin $rfin-$nSRuns
				echo ln $rfin-$nSRuns $rfin
				\mv -f $ofin $rfin-$nSRuns
				\ln -sf $rfin-$nSRuns $rfin
			endif
		endif
	endif
else
# Jacobian
	foreach i ( $ext )
        	zip -u $root-jacobian.zip $root.*.$i >& /dev/null
	end
# if by any chance smartrst1 (job *.1 crashed) missed to do this ...
	if( -e $root-serial.runs ) then
		@ nSRuns = `cat $root-serial.runs`
		rm -f $root-serial.runs_restart $root-serial.runs
		@ nJRuns = `cat $root-jacobian.runs`
		@ loop = 0
		while( $nSRuns > $loop )
			@ loop = $loop + 1
			zip -um $root-jacobian_$nJRuns.zip $root-serial_$loop.zip >& /dev/null
		end
		zip -u $root-jacobian_$nJRuns.zip $root.mtt $root.seo $root.jst $root.jac $root.jco $root.par >& /dev/null
	endif
endif
exit 0
