#!/bin/tcsh -f
echo 'variables="particle number", "x [m]", "y [m]", "z [m]", "Time [a]", "zone number"'
sed "1,3d" $1 | awk 'BEGIN{nn=0} {if($1>nn) {nn=$1;nt[nn]=0;} i=$1; no[i,nt[i]]=i; x[i,nt[i]]=$2; y[i,nt[i]]=$3; z[i,nt[i]]=$4; t[i,nt[i]]=$5/365; zn[i,nt[i]]=$6; nt[i]++;  } END { for(i=1;i<=nn;i++) { printf "zone t=\"particle %i\"\n", i; for(j=0;j<nt[i];j++) printf "%d %g %g %g %g %d\n", no[i,j],x[i,j],y[i,j],z[i,j],t[i,j],zn[i,j] } }'
